# Generated by Django 5.1.4 on 2025-01-05 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subjectname", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="marks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subjectmarks", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to="helloapi.user",
                    ),
                ),
                (
                    "subject_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject",
                        to="helloapi.subject",
                    ),
                ),
            ],
        ),
    ]
