# Generated by Django 5.1.4 on 2025-01-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloapi", "0002_subject_marks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subject",
        ),
        migrations.AddField(
            model_name="user",
            name="subject_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub",
                to="helloapi.subject",
            ),
            preserve_default=False,
        ),
    ]
