# Generated by Django 5.1.4 on 2025-01-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloapi", "0003_remove_user_subject_user_subject_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subjectname",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name="user",
            name="subject_id",
        ),
        migrations.AddField(
            model_name="user",
            name="subject_id",
            field=models.ManyToManyField(
                default="3", null=True, related_name="sub", to="helloapi.subject"
            ),
        ),
    ]
