version: "3.11"

services:
  web:
  
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 & FLASK_APP=flask-api/app.py flask run --host=0.0.0.0 --port=5000"
    container_name: loginapp
    volumes:
      - .:/loginapp
    ports:
      - "8000:8000"
      - "5000:5000"
   
    depends_on:
      - dblogin
      - redis
    
  dblogin:
    platform: linux/amd64
    container_name: dblogin
    image: postgres:15
    environment:
      - POSTGRES_DB=student
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vaibhavi
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: django-redis
    ports:
      - "6379:6379"

